# Generated by Django 5.2.4 on 2025-07-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'db_table': 'tb_organizacoes',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='chatbot.organizacao')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'tb_administradores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('whatsapp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(blank=True, null=True)),
                ('contexto', models.JSONField(blank=True, default=dict)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='chatbot.organizacao')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'tb_usuarios',
            },
        ),
        migrations.CreateModel(
            name='Safra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=255)),
                ('ano_safra', models.CharField(blank=True, max_length=10, null=True)),
                ('area_plantada_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produtividade', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidade_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safras', to='chatbot.usuario')),
            ],
            options={
                'verbose_name': 'Safra',
                'verbose_name_plural': 'Safras',
                'db_table': 'tb_safras',
            },
        ),
        migrations.CreateModel(
            name='ProdutoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_produto', models.CharField(max_length=50)),
                ('unidade_medida', models.CharField(max_length=20)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_estoque', to='chatbot.usuario')),
            ],
            options={
                'verbose_name': 'Produto em Estoque',
                'verbose_name_plural': 'Produtos em Estoque',
                'db_table': 'tb_produtos_estoque',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField(blank=True, null=True)),
                ('resposta_chatbot', models.TextField(blank=True, null=True)),
                ('entidades', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='chatbot.usuario')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'db_table': 'tb_interacoes',
            },
        ),
    ]
