# Generated by Django 5.2.4 on 2025-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_criar_organizacao_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('key', models.CharField(help_text="Chave única para identificar o prompt no código (ex: 'welcome_message')", max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='O texto que será enviado para o usuário. Pode conter {placeholders}.')),
                ('description', models.CharField(blank=True, help_text='Descrição interna para explicar onde este prompt é usado.', max_length=255)),
            ],
            options={
                'verbose_name': 'Prompt do Chatbot',
                'verbose_name_plural': 'Prompts do Chatbot',
                'db_table': 'tb_prompts',
            },
        ),
    ]
